name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - name: Linux-x86_64
            os: ubuntu-latest
            cibw_archs: x86_64
          - name: Linux-aarch64
            os: ubuntu-latest
            cibw_archs: aarch64
          - name: macOS-x86_64
            os: macos-13  # Intel
            cibw_archs: x86_64
          - name: macOS-arm64
            os: macos-14  # Apple Silicon
            cibw_archs: arm64
          - name: Windows-x86_64
            os: windows-latest
            cibw_archs: AMD64

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.21.0
      env:
        CIBW_BUILD: cp311-* cp312-* cp313-*
        CIBW_ARCHS: ${{ matrix.platform.cibw_archs }}
        PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
        CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=${{
          matrix.platform.cibw_archs == 'arm64' && '11.0' || '10.12'
          }}

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.platform.name }}
        path: wheelhouse/*.whl
